/**
 * RokNewsFlash Module
 *
 * @package		Joomla
 * @subpackage	RokNewsFlash Module
 * @copyright Copyright (C) 2009 RocketTheme. All rights reserved.
 * @license http://www.gnu.org/copyleft/gpl.html GNU/GPL, see RT-LICENSE.php
 * @author RocketTheme, LLC
 *
 */

eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('m 1k=q 16({18:[1b,1j],1q:1.2,o:{D:X,T:1p,y:1r},1v:4(b,c){3.19(c);3.v=1d.1f(b)||1h;3.v.L({\'N\':3.u.f(3),\'K\':3.p.f(3)});3.e=3.v.11(\'13 14\');3.8=0;3.k=[];3.e.1a().n(\'R\',\'1e\');m d=3;3.e.1g(4(a,i){a.n(\'R\',\'1y\');3.k[i]=q 1m.1n(a,{y:3.o.y,1o:4(){d.s=X;3.e.n(\'r\',\'C\');a.n(\'r\',\'1s\')}.f(3),1t:4(){d.s=1u;l(!a.1w(\'9\').10()){a.n(\'r\',\'C\')}}}).B(\'9\',1);l(!i)6;a.12({\'9\':0,\'r\':\'C\'})},3);l(3.o.D)3.S();3.x=\'u\';15.E(\'17\',3.p.f(3));6 3},S:4(){m a=q F(\'G\',{\'H\':\'D\'}).I(3.v,\'1c\');3.J=q F(\'G\',{\'H\':\'5-h\'}).I(a).B(\'O\',\'<A>&1i;-</A>\');3.M=q F(\'G\',{\'H\':\'5-7\'}).I(a).B(\'O\',\'<A>-&1l;</A>\');3.J.E(\'P\',3.Q.f(3));3.M.E(\'P\',3.7.f(3));3.J.L({\'N\':4(){3.t(\'5-h-w\')},\'K\':4(){3.j(\'5-h-w\').j(\'5-h-g\')},\'U\':4(){3.t(\'5-h-g\')},\'V\':4(){3.j(\'5-h-g\')}});3.M.L({\'N\':4(){3.t(\'5-7-w\')},\'K\':4(){3.j(\'5-7-w\').j(\'5-7-g\')},\'U\':4(){3.t(\'5-7-g\')},\'V\':4(){3.j(\'5-7-g\')}});6 3},Q:4(){l(3.s)6 3;m a=(!3.8)?3.e.W-1:3.8-1;3.k[3.8].z(\'9\',0);3.k[a].z(\'9\',1);3.8=a;6 3},7:4(){l(3.s)6 3;m a=(3.8==3.e.W-1)?0:3.8+1;3.k[3.8].z(\'9\',0);3.k[a].z(\'9\',1);3.8=a;6 3},p:4(){l(3.x==\'p\')6 3;3.x=\'p\';3.Y=3.7.1x(3.o.T+3.o.y,3);6 3},u:4(){3.x=\'u\';$Z(3.Y);6 3}});',62,97,'|||this|function|control|return|next|current|opacity|||||news|bind|down|prev||removeClass|fx|if|var|setStyle|options|play|new|visibility|transitioning|addClass|stop|element|hover|status|duration|start|span|set|hidden|controls|addEvent|Element|div|class|inject|arrowPrev|mouseleave|addEvents|arrowNext|mouseenter|html|click|previous|position|addControls|delay|mousedown|mouseup|length|true|timer|clear|toInt|getElements|setStyles|ul|li|window|Class|domready|Implements|setOptions|getParent|Options|top|document|relative|id|each|null|lt|Events|RokNewsFlash|gt|Fx|Tween|onStart|2000|version|800|visible|onComplete|false|initialize|getStyle|periodical|absolute'.split('|'),0,{}))
